add_newline = false
continuation_prompt = "[|](bold green) "
command_timeout = 200
scan_timeout = 10

container.disabled = true
docker_context.disabled = true
localip.disabled = true

[gcloud]
symbol = "ó±‡¶ "

[hostname]
ssh_only = false
format = '[$hostname$ssh_symbol]($style) in '
# ssh_symbol = ' ğŸŒ'
ssh_symbol = " î¬"

[sudo]
disabled = false
format = "with [$symbol]($style) "
# symbol = "â˜£ï¸ "
symbol = "ó°„ "

[username]
show_always = true
format = "[$user]($style)@"

[custom.ssh]
command = """ echo "${SSH_CLIENT}" | awk -F' ' '{print $1}' """
when = """ test ! -z "${SSH_CLIENT}" """
# format = "via [ğŸ¡ $output]($style) "
# format = "via [ó°£€ $output]($style) "
format = "via [ïŒ¨ $output]($style) "

[custom.direnv]
command = """ echo "${DIRENV_FILE}" | awk -F'/' '{print $(NF-1)"/"$(NF)}' """
when = """ test ! -z "${DIRENV_FILE}" """
# format = "with [ğŸ“‚ $output]($style) "
format = "with [ï“ $output]($style) "

[env_var.CHEZMOI_ARGS]
variable = "CHEZMOI_ARGS"
# symbol = "ğŸ "
symbol = "î¬†"
style = "red bold"
format = "in [$symbol chezmoi]($style) "


# Nerd Font Stuff

[os.symbols]
Alpine = "ïŒ€ "
Arch = "ïŒƒ "
Debian = "ïŒ† "
Gentoo = "ïŒ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Macos = "ïŒ‚ "
OpenBSD = "ó°ˆº "
Ubuntu = "ïŒ› "

[c]
symbol = "î˜ "

[directory]
read_only = " ó°Œ¾"

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ó°› "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ó°— "

[python]
symbol = "îˆµ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "ó±˜— "
